name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy to Supabase'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@github.com"

      - name: Install Supabase CLI
        id: deploy
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
          supabase link --project-ref $PROJECT_ID
          output=$(supabase db push | tail -n 1)
          echo "result=$output" >> $GITHUB_OUTPUT

      - name: Tag repo with migration deployment tag
        if: success() && steps.deploy.outputs.result != 'Remote database is up to date.'
        run: |
          migration_tag="supabase-db-deployment-$(date +%Y%m%d%H%M%S)"
          git tag "$migration_tag"
          git push origin "$migration_tag"
